# Generated by Django 2.2.4 on 2021-03-03 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HangarAndMechlabApp', '0002_auto_20210303_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chassis',
            name='hangar_src',
        ),
        migrations.RemoveField(
            model_name='chassis',
            name='mechlab_src',
        ),
        migrations.RemoveField(
            model_name='chassis',
            name='tot_bSlots',
        ),
        migrations.RemoveField(
            model_name='chassis',
            name='tot_eSlots',
        ),
        migrations.RemoveField(
            model_name='chassis',
            name='tot_mSlots',
        ),
        migrations.RemoveField(
            model_name='chassis',
            name='tot_oSlots',
        ),
    ]
