# Generated by Django 2.2.4 on 2021-03-04 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HangarAndMechlabApp', '0003_auto_20210303_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='displayChassis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('tons', models.IntegerField()),
                ('tot_eSlots', models.IntegerField()),
                ('tot_bSlots', models.IntegerField()),
                ('tot_mSlots', models.IntegerField()),
                ('tot_oSlots', models.IntegerField()),
                ('hanagar_src', models.TextField()),
                ('mechlab_src', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='chassis',
            name='id',
        ),
        migrations.RemoveField(
            model_name='chassis',
            name='name',
        ),
        migrations.RemoveField(
            model_name='chassis',
            name='tons',
        ),
        migrations.AddField(
            model_name='chassis',
            name='displaychassis_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='HangarAndMechlabApp.displayChassis'),
            preserve_default=False,
        ),
    ]
