# Generated by Django 2.2.4 on 2021-03-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HangarAndMechlabApp', '0007_chassis_tons_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaychassis',
            name='hangar_src',
            field=models.ImageField(upload_to=None),
        ),
        migrations.AlterField(
            model_name='displaychassis',
            name='mechlab_src',
            field=models.ImageField(upload_to=None),
        ),
    ]
