# Generated by Django 2.2.4 on 2021-03-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HangarAndMechlabApp', '0008_auto_20210304_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaychassis',
            name='hangar_src',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='displaychassis',
            name='mechlab_src',
            field=models.TextField(),
        ),
    ]
