# Generated by Django 2.2.4 on 2021-03-05 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HangarAndMechlabApp', '0009_auto_20210304_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='bSlots',
        ),
        migrations.RemoveField(
            model_name='part',
            name='eSlots',
        ),
        migrations.RemoveField(
            model_name='part',
            name='id',
        ),
        migrations.RemoveField(
            model_name='part',
            name='mSlots',
        ),
        migrations.RemoveField(
            model_name='part',
            name='mech',
        ),
        migrations.RemoveField(
            model_name='part',
            name='name',
        ),
        migrations.RemoveField(
            model_name='part',
            name='oSlots',
        ),
        migrations.AlterField(
            model_name='displaychassis',
            name='tot_bSlots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='displaychassis',
            name='tot_eSlots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='displaychassis',
            name='tot_mSlots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='displaychassis',
            name='tot_oSlots',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='templatePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('eSlots', models.IntegerField(default=0)),
                ('bSlots', models.IntegerField(default=0)),
                ('mSlots', models.IntegerField(default=0)),
                ('oSlots', models.IntegerField(default=0)),
                ('mech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='HangarAndMechlabApp.displayChassis')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='templatepart_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='HangarAndMechlabApp.templatePart'),
            preserve_default=False,
        ),
    ]
