# Generated by Django 2.2.4 on 2021-03-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HangarAndMechlabApp', '0012_auto_20210304_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='equips',
            field=models.ManyToManyField(related_name='assign_part', to='HangarAndMechlabApp.Equip'),
        ),
    ]
