# Generated by Django 2.2.4 on 2021-03-05 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HangarAndMechlabApp', '0013_auto_20210304_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='equips',
            new_name='equipped',
        ),
    ]
