# Generated by Django 2.2.4 on 2021-03-05 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HangarAndMechlabApp', '0014_auto_20210304_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='equipped',
        ),
    ]
