# Generated by Django 2.2.4 on 2021-02-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='Placeholder Description', max_length=255),
            preserve_default=False,
        ),
    ]
