# Generated by Django 2.2.4 on 2021-02-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_and_registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contained_text', models.TextField()),
                ('user', models.ManyToManyField(related_name='message', to='login_and_registration.User')),
            ],
        ),
    ]
